{"uuid": "c2af76e0-3cdb-48c4-8d70-dbdaba9e4b5a", "children": ["438aa9ea-ab33-449d-a2d1-406c7147fce2"], "befores": [{"name": "registered_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\WebDriver\\bin\\Diplom_2\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\WebDriver\\bin\\Diplom_2\\conftest.py\", line 22, in registered_user\n    assert response.status_code == 200\n"}, "start": 1755429716213, "stop": 1755429716569}], "start": 1755429716213, "stop": 1755429716575}