{"name": "Login with invalid credentials", "status": "passed", "start": 1755429846873, "stop": 1755429847232, "uuid": "77775fa8-1cbe-4d24-aa08-341a33ef31ec", "historyId": "b09ebfcefb960e695e038510e71f6c72", "testCaseId": "b09ebfcefb960e695e038510e71f6c72", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_credentials", "labels": [{"name": "feature", "value": "User Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "dea-1611"}, {"name": "thread", "value": "16536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}